# Generated by Django 4.1.2 on 2022-10-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128, unique=True)),
                ('ipaddr', models.CharField(max_length=32)),
                ('desc', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
